services:
  web:
    ports:
      - "3000:3000"
    restart: on-failure

  redis:
    ports:
      - "6379:6379"
    restart: on-failure

secrets:
  redis_password:
    file: ./redis_password.txt # Mendefinisikan secret dari file lokal