services:
  web:
    build: .
    image: mynextapp:latest
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD} # <-- Mengambil dari .env
  redis:
    image: redis:alpine
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} # <-- Meneruskan dari .env