services:
  web:
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password

  redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    command: sh -c "redis-server --requirepass \"$$(cat /run/secrets/redis_password)\""
    secrets:
      - redis_password

secrets:
  redis_password:
    external: true
